ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
