ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
