ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/codecs
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/isps
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/pproc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_cherry/jpeg_10

obj-$(CONFIG_MSMB_CAMERA) += msm.o
obj-$(CONFIG_MSMB_CAMERA) += camera/
obj-$(CONFIG_MSMB_CAMERA) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA) += sensor/
obj-$(CONFIG_MSMB_CAMERA) += pproc/
obj-$(CONFIG_MSMB_CAMERA) += isp/
obj-$(CONFIG_MSMB_CAMERA) += ispif/
obj-$(CONFIG_MSMB_JPEG) += jpeg_10/
obj-$(CONFIG_MSMB_CAMERA) += msm_buf_mgr/
